### PR TITLE
add the publishedDate as lastmod tag

### PR DESCRIPTION
**Pull request by TheoLeanse**
/cc @wheresrhys @matthew-andrews

### CODE REVIEW

**Comment by wheresrhys** [comment]
:+1:

**Comment by matthew-andrews** [comment]
hold on

**Comment by matthew-andrews** [comment]
what is this trying to do? …… once we generate the sitemaps these will slowly drift out of date because we don't update old sitemaps once they're generated ………

**Comment by TheoLeanse** [comment]
It's to address incorrect pub dates in google, which I hear are to do with lacking published date information in the sitemap for articles, and markup to state the date in the page itself.

**Comment by matthew-andrews** [comment]
hmm, ok well worth a try

**Comment by matthew-andrews** [comment]
do we need to regenerate the old sitemaps when the old articles' publish date changes though?

**Comment by TheoLeanse** [comment]
I guess we need to update the date in google when an article's publish date changes?

**Comment by matthew-andrews** [comment]
hmm, i would have thought it could pick it up from the article itself OK but clearly something's up :-/

**Pull request merged**
